// OROSSParser.idl : IDL source for OROSSParser
//

// This file will be processed by the MIDL tool to
// produce the type library (OROSSParser.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

    typedef [v1_enum] enum
    {
        Create = 0,
        Update,
        Rebuild,
        AddROS,
        ROSOnly,
        OROSSConvert,
        PreView,
        WebUpdate,
    }modeName;


    [
        object,
        uuid(6B3F19E1-5F18-48B2-B49D-C411B990AAAF),
        dual,
        helpstring("IOROSSParser Interface"),
        pointer_default(unique),
    ]
    interface IOROSSParser : IDispatch
    {
        [id(1), helpstring("method Init")] HRESULT Init(modeName name, BSTR config, [out, retval] long *hRes );
        [id(2), helpstring("method Terminate")] HRESULT Terminate([out, retval] long *hRes );
        [id(3), helpstring("method AddPart")] HRESULT AddPart( BSTR Name, [out, retval] long *hRes );
        [id(4), helpstring("method AddTile")] HRESULT AddTile( BSTR Name, [out, retval] long *hRes );
        [id(5), helpstring("method AppendTile")] HRESULT AppendTile( BSTR Str, [out, retval] long *hRes );
        [id(6), helpstring("method AddPara")] HRESULT AddPara( long Num, BSTR Para, [out, retval] long *hRes );
        [id(7), helpstring("method AddExamplesToPara")] HRESULT AddExamplesToPara( BSTR Examples, [out, retval] long *hRes );
        [id(8), helpstring("method AddRule")] HRESULT AddRule( BSTR Num, BSTR Rule, [out, retval] long *hRes );
        [id(9), helpstring("method AddOrthogr")] HRESULT AddOrthogr( BSTR Orthogr, BSTR Formula, BSTR Example, BSTR Rest, long IsActive, long IsPrefix, [out, retval] long *hRes );
        [id(10), helpstring("method AddArticle")] HRESULT AddArticle( BSTR Title, BSTR Article, [out, retval] long *hRes );
        [id(11), helpstring("method AddInfoToRule")] HRESULT AddInfoToRule( BSTR Info, [out, retval] long *hRes );
        [id(12), helpstring("method AddRuleTitle")] HRESULT AddRuleTitle(BSTR Num, BSTR Title, [out, retval] long *hRes);
        [id(13), helpstring("method AddFootNote")] HRESULT AddFootNote(long ID, BSTR Text, [out, retval] long *hRes);
        //
        [id(14), helpstring("method LoadArticles")] HRESULT LoadArticles( BSTR Dic, [out, retval] long *hRes );
        [id(15), helpstring("method ReadOROSS")] HRESULT ReadOROSS(BSTR Dic, [out, retval] long *hRes);
        [id(16), helpstring("method LoadWords")] HRESULT LoadWords(BSTR Dic, [out, retval] long *hRes);
        [id(17), helpstring("method SaveTitle")] HRESULT SaveTitle(BSTR Title, [out, retval] long *hRes);
        [id(18), helpstring("method SaveArticle")] HRESULT SaveArticle(BSTR Title, BSTR Article, [out, retval] long *hRes);
        [id(19), helpstring("method PreViewArticle")] HRESULT PreViewArticle([out, retval] long *hRes);
    };

[
    uuid(81947C63-F771-4EE8-9340-90861817047E),
    version(1.0),
]

library OROSSParserLib
{
        importlib("stdole32.tlb");
        importlib("stdole2.tlb");
        [
            uuid(14712ED3-9863-4501-8DB5-E8769D44D4D8),
            helpstring("OROSSParser Class")
        ]

        coclass OROSSParser
        {
            [default] interface IOROSSParser;

        };
};
